version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - update-types: ["version-update:semver-patch"]
      - update-types: ["version-update:semver-minor"]

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - update-types: ["version-update:semver-patch"]
      - update-types: ["version-update:semver-minor"]
