# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: true

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-json # checks json files for parseable syntax.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-symlinks # checks for symlinks which do not point to anything.
      - id: check-toml # checks toml files for parseable syntax.
      - id: check-vcs-permalinks # ensures that links to vcs websites are permalinks.
      - id: check-xml # checks xml files for parseable syntax.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        args: [--disable-indent-size, --disable-max-line-length]

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo-fmt
        language: system
        types: [rust]
        entry: cargo fmt
        args:
          - --all
          - --check
          - --

      - id: cargo-clippy
        name: cargo-clippy
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo clippy
        args:
          - --workspace
          - --all-features
          - --all-targets
          - --no-deps
          - --
          - -Dwarnings
          - -Dclippy::all

      - id: cargo-doc
        name: cargo-doc
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo doc
        args:
          - --config=build.rustdocflags = ["-Dwarnings", "-Drustdoc::all"]
          - --workspace
          - --all-features
          - --no-deps
          - --
