# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: true

default_install_hook_types:
    - pre-commit
    - commit-msg

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-added-large-files # Prevents giant files from being committed.
          - id: check-case-conflict # Checks for files that would conflict in case-insensitive filesystems.
          - id: check-merge-conflict # Checks for files that contain merge conflict strings.
          - id: check-symlinks # Checks for symlinks which do not point to anything.
          - id: check-vcs-permalinks # Ensures that links to vcs websites are permalinks.
          - id: destroyed-symlinks # Detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.

    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.18.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ["@commitlint/config-conventional"]

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: "v0.42.0"
      hooks:
          - id: markdownlint

    - repo: https://github.com/ComPWA/taplo-pre-commit
      rev: v0.9.3
      hooks:
          - id: taplo-format
          - id: taplo-lint

    - repo: local
      hooks:
          - id: prettier
            name: prettier
            entry: prettier --write --ignore-unknown --cache --cache-location=target/.prettier-cache
            language: node
            types: [text]
            stages: [commit]
            additional_dependencies: ["prettier@3"]

          - id: cargo-fmt
            name: cargo-fmt
            language: system
            types: [rust]
            entry: cargo fmt
            args:
                - --all
                - --

          - id: cargo-clippy
            name: cargo-clippy
            language: system
            types: [rust]
            pass_filenames: false
            entry: cargo clippy
            args:
                - --workspace
                - --all-features
                - --all-targets
                - --
                - -Dwarnings
                - -Dclippy::all

          - id: cargo-doc
            name: cargo-doc
            language: system
            types: [rust]
            pass_filenames: false
            entry: cargo doc
            args:
                - --config=build.rustdocflags = ["-Dwarnings", "-Drustdoc::all"]
                - --workspace
                - --all-features
                - --no-deps
                - --
